INSERT INTO PERSONS (NAME_TAX_CODE,SURNAME_TAX_CODE,DATE_BIRTH_TAX_CODE,CITY_TAX_CODE,VALIDATION_CHARACTER_TAX_CODE ,NAME,SURNAME,CITY_BIRTH,DATE_BIRTH,GENDER)
VALUES('MRA','RSS','80L10','H501','Z','MARIO','ROSSI','ROMA','1980-10-07',0);
INSERT INTO PERSONS (NAME_TAX_CODE,SURNAME_TAX_CODE,DATE_BIRTH_TAX_CODE,CITY_TAX_CODE,VALIDATION_CHARACTER_TAX_CODE ,NAME,SURNAME,CITY_BIRTH,DATE_BIRTH,GENDER)
VALUES('MRA','RSS','80L11','H501','Z','MARIO','ROSSO','ROMA','1980-11-07',0);
INSERT INTO PERSONS (NAME_TAX_CODE,SURNAME_TAX_CODE,DATE_BIRTH_TAX_CODE,CITY_TAX_CODE,VALIDATION_CHARACTER_TAX_CODE ,NAME,SURNAME,CITY_BIRTH,DATE_BIRTH,GENDER)
VALUES('MRA','RSS','80L12','H501','Z','MARIA','ROSSO','ROMA','1980-12-07',1);
INSERT INTO PERSONS (NAME_TAX_CODE,SURNAME_TAX_CODE,DATE_BIRTH_TAX_CODE,CITY_TAX_CODE,VALIDATION_CHARACTER_TAX_CODE ,NAME,SURNAME,CITY_BIRTH,DATE_BIRTH,GENDER)
VALUES('MRA','RSS','80L13','H501','Z','MARY','ROSSO','ROMA','1980-13-07',1);
INSERT INTO CITIES (CITY,CITY_CODE) VALUES(UPPER('Roma'),'H501');
INSERT INTO CITIES (CITY,CITY_CODE) VALUES(UPPER('Ascoli Piceno'),'A462');
INSERT INTO CITIES (CITY,CITY_CODE) VALUES(UPPER('Torino'),'L219');
INSERT INTO CITIES (CITY,CITY_CODE) VALUES(UPPER('Bologna'),'A944');
